export const recipes = [
  { slug:"grilled-chicken-power-bowl", name:"Grilled chicken power bowl", type:"Lunch", image:"https://images.unsplash.com/photo-1532550907401-a500c9a57435?auto=format&fit=crop&w=1000&q=85", protein:52, calories:610, time:30, reason:"High-protein training-day meal supporting muscle retention while keeping portions predictable.", tags:["High protein","Fat loss","Training day"], ingredients:["200 g chicken breast","3/4 cup cooked rice","2 cups mixed vegetables","1 tsp olive oil","Paprika, garlic, black pepper"], steps:["Season and grill the chicken until cooked through.","Steam or stir-fry the vegetables.","Serve over rice and add lemon or a light yoghurt sauce."] },
  { slug:"tuna-avocado-crunch-bowl", name:"Tuna avocado crunch bowl", type:"Lunch", image:"https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=1000&q=85", protein:38, calories:480, time:12, reason:"Fast, fibre-rich lunch for days when cooking ambition has left the building.", tags:["Quick","Heart-conscious","Budget"], ingredients:["1 tin tuna in spring water","1/4 avocado","Mixed salad leaves","Tomato and cucumber","1/2 cup beans"], steps:["Drain the tuna.","Combine the vegetables and beans.","Top with tuna and avocado; season with lemon and pepper."] },
  { slug:"protein-oats-banana", name:"Protein oats with banana", type:"Breakfast", image:"https://images.unsplash.com/photo-1490645935967-10de6ba17061?auto=format&fit=crop&w=1000&q=85", protein:31, calories:520, time:10, reason:"Slow-release carbohydrates and protein for a satisfying breakfast or pre-workout meal.", tags:["Breakfast","Pre-workout","High fibre"], ingredients:["1/2 cup oats","250 ml low-fat milk","1 banana","1/2 scoop whey","Cinnamon"], steps:["Cook oats with milk.","Remove from heat and mix in whey.","Top with banana and cinnamon."] },
  { slug:"post-workout-shake", name:"Banana peanut-butter recovery shake", type:"Post-workout", image:"https://images.unsplash.com/photo-1579722821273-0f6c7d44362f?auto=format&fit=crop&w=1000&q=85", protein:24, calories:330, time:4, reason:"Convenient protein after evening training, including your daily 5 g creatine.", tags:["Post-workout","Fast","Your plan"], ingredients:["1 scoop Titan True Whey","1 banana","1 tbsp peanut butter","300 ml water","5 g creatine"], steps:["Add all ingredients to a blender.","Blend until smooth.","Drink after training or use as a protein-gap snack."] },
  { slug:"lean-mince-sweet-potato", name:"Lean mince and sweet potato skillet", type:"Dinner", image:"https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=1000&q=85", protein:45, calories:590, time:35, reason:"Comforting dinner with controlled fat, fibre and enough protein to finish the day strongly.", tags:["Dinner","Meal prep","High protein"], ingredients:["180 g lean beef mince","1 medium sweet potato","Spinach","Onion","Tomato"], steps:["Brown the mince with onion.","Add diced sweet potato and tomato with a splash of water.","Cover until tender, then fold in spinach."] },
  { slug:"greek-yoghurt-fruit", name:"Greek yoghurt and fruit cup", type:"Snack", image:"https://images.unsplash.com/photo-1488477181946-6428a0291777?auto=format&fit=crop&w=1000&q=85", protein:17, calories:220, time:3, reason:"A rotating high-protein snack that is easy to carry and gentler than another full meal.", tags:["Snack","No cook","High protein"], ingredients:["170 g plain Greek yoghurt","1/2 cup berries or chopped apple","Cinnamon"], steps:["Spoon yoghurt into a bowl.","Add fruit and cinnamon."] }
];

export const exercises = [
 {name:"Push-ups", group:"Chest + triceps", sets:"3 × max clean reps", video:"https://www.youtube.com/results?search_query=proper+push+up+form", icon:"pushup"},
 {name:"Dumbbell floor press", group:"Chest + triceps", sets:"3 × 10–12", video:"https://www.youtube.com/results?search_query=dumbbell+floor+press+proper+form", icon:"press"},
 {name:"One-arm dumbbell row", group:"Back + biceps", sets:"3 × 10–12 each", video:"https://www.youtube.com/results?search_query=one+arm+dumbbell+row+proper+form", icon:"row"},
 {name:"Dumbbell shoulder press", group:"Shoulders", sets:"3 × 10–12", video:"https://www.youtube.com/results?search_query=dumbbell+shoulder+press+proper+form", icon:"shoulder"},
 {name:"Goblet squat", group:"Legs", sets:"3 × 12–15", video:"https://www.youtube.com/results?search_query=goblet+squat+proper+form", icon:"squat"},
 {name:"Forearm plank", group:"Core", sets:"3 × 30–60 sec", video:"https://www.youtube.com/results?search_query=forearm+plank+proper+form", icon:"plank"},
 {name:"Bicycle crunch", group:"Core", sets:"3 × 20", video:"https://www.youtube.com/results?search_query=bicycle+crunch+proper+form", icon:"crunch"},
 {name:"Romanian deadlift", group:"Hamstrings + glutes", sets:"3 × 10–12", video:"https://www.youtube.com/results?search_query=dumbbell+romanian+deadlift+proper+form", icon:"deadlift"}
];
